### ISSUE TITLE
spark, particle not working???

### ISSUE THREAD

**Issue by hoodpablo** [mwittig/pimatic-johnny-five#3]
Hi, to make spark or particle work, I had to modify board-manager.coffee some lines to:
`when 'spark-io' then (
          Particle = require 'particle-io'
          @board = new BoardWrapper(_.assign(options, {io: new Particle({
    token: options.token,
    deviceId: options.deviceId
  })}))
        )`

I am a noob in this, but it seem to work fine for me (test it and working for 4 relays),  am I doing something wrong or should do something else to make it work or is it an issue???

**Comment by mwittig** [comment]
Sorry about this. 'spark-io' was just a mockup I had in place for testing and then I forgot to switch it back to the actual implementation. Your initialization code is right and I'll oublish a new release shortly. It is great the the particle stuff is working fine for you. Please let me know if you have ideas for improving the plugin!

**Comment by mwittig** [comment]
Note, I have also changed the boardType value from 'particle-io' to 'patrticle-io' to align with the documentation given in the README!

**Comment by mwittig** [comment]
Released 0.8.7

**Comment by hoodpablo** [comment]
Perfect, thanks I will be testing it and give some feedback!!!
