### ISSUE TITLE
Board not found (PCF8574)

### ISSUE THREAD

**Issue by joerg65** [mwittig/pimatic-johnny-five#57]
I try to make use the PCF8574 expander but when I start the pimatic I get errors:

15:53:54.026 [pimatic-johnny-five] [BoardManager] Error: Board not found
15:53:54.040 [pimatic-johnny-five] [BoardManager] Creation of board 1 raised exception:Error: Board not found
15:53:54.055 [pimatic-johnny-five] [BoardManager] Error: Board not found
15:53:54.066 [pimatic-johnny-five] [BoardManager] Creation of board 2 raised exception:Error: Board not found
15:53:58.773 [pimatic-johnny-five] [BoardManager] Error: Board not found
15:53:58.786 [pimatic] Error loading device "jf-b-1": Board not found
15:53:59.354 [pimatic] Error loading device "jf-r-1": Board not found

I tried also without the address statements and with the real path to the i2c-device in port statements.

This is the config:
```
{
  "//": "Please only change this file when pimatic is NOT running, otherwise pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 80
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "removed"
    },
    "httpsServer": {},
    "cors": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    },
    {
      "plugin": "johnny-five",
      "boards": [
        {
          "id": "1",
          "boardType": "expander",
          "address": "32",
          "port": "1",
          "controller": "PCF8574"
        },
        {
          "id": "2",
          "boardType": "expander",
          "address": "33",
          "port": "1",
          "controller": "PCF8574"
        }
      ]
    }
  ],
  "devices": [
    {
      "id": "jf-b-1",
      "class": "JohnnyFiveButton",
      "name": "Button (pin 1)",
      "pin": "1",
      "boardId": "1"
    },
    {
      "id": "jf-r-1",
      "name": "Johnny Five Relay",
      "class": "JohnnyFiveRelay",
      "boardId": "2",
      "pin": "1",
      "type": "NO"
    }
  ],
  "rules": [],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": []
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "admin",
      "password": "",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "database": "write",
        "config": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}
```

sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: 20 21 -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --  

gpio -v
gpio version: 2.44
Copyright (c) 2012-2017 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Model B, Revision: 02, Memory: 512MB, Maker: Egoman 
  * Device tree is enabled.
  *--> Raspberry Pi Model B Rev 2
  * This Raspberry Pi supports user-level GPIO access.

ls -l /dev/i2c-1
crw-rw---- 1 root i2c 89, 1 May 27 15:40 /dev/i2c-1

**Comment by mwittig** [comment]
Hi, 

thanks for using pimatic-johnny-five! I think you're missing the configuration for the base board, i.e. raspi-io. Please try the following config. Note the modified "port" values for the two expander board types as the port must point to the raspi-io board.

```
{
      "plugin": "johnny-five",
      "boards": [
       {
          "id": "0",
          "boardType": "raspi-io",
        },
        {
          "id": "1",
          "boardType": "expander",
          "address": "32",
          "port": "0",
          "controller": "PCF8574"
        },
        {
          "id": "2",
          "boardType": "expander",
          "address": "33",
          "port": "0",
          "controller": "PCF8574"
        }
      ]
    }

**Comment by joerg65** [comment]
Thank you! I was already probing with a parent board but your tip solved it now. It works.

**Comment by mwittig** [comment]
That's great! I am glad it is working for you know. If you have further questions or suggestions for improvement please open a new issue or use the pimatic user forum at https://forum.pimatic.org/

If you like this plugin, please consider &#x2605; starring  [the project on github](https://github.com/mwittig/pimatic-johnny-five). Contributions to the project are  welcome.
